// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwpE2f7joQlMMhXyEaRgJx4LrtTKMZmI4',
    appId: '1:759330275647:web:159ac6e76d27cd1c99138a',
    messagingSenderId: '759330275647',
    projectId: 'rakna-47fbd',
    authDomain: 'rakna-47fbd.firebaseapp.com',
    storageBucket: 'rakna-47fbd.appspot.com',
    measurementId: 'G-JTG8YNZ26G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNVKL1X8CI2xR2iRuKdUDsM4yxMApN7T4',
    appId: '1:759330275647:android:7bd81b034466eb0099138a',
    messagingSenderId: '759330275647',
    projectId: 'rakna-47fbd',
    storageBucket: 'rakna-47fbd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkiD5DbS1clNuL_JBhxjRK28uvpCgrQmM',
    appId: '1:759330275647:ios:c3be52892ea4ece399138a',
    messagingSenderId: '759330275647',
    projectId: 'rakna-47fbd',
    storageBucket: 'rakna-47fbd.appspot.com',
    androidClientId: '759330275647-dsvmlbv4pt4tnn4rrtq9ei2l49u4h3eq.apps.googleusercontent.com',
    iosClientId: '759330275647-cajfpqlnr6r1h3l7osko6p2m046k6fsf.apps.googleusercontent.com',
    iosBundleId: 'com.example.cleanRakna',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkiD5DbS1clNuL_JBhxjRK28uvpCgrQmM',
    appId: '1:759330275647:ios:c3be52892ea4ece399138a',
    messagingSenderId: '759330275647',
    projectId: 'rakna-47fbd',
    storageBucket: 'rakna-47fbd.appspot.com',
    androidClientId: '759330275647-dsvmlbv4pt4tnn4rrtq9ei2l49u4h3eq.apps.googleusercontent.com',
    iosClientId: '759330275647-cajfpqlnr6r1h3l7osko6p2m046k6fsf.apps.googleusercontent.com',
    iosBundleId: 'com.example.cleanRakna',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwpE2f7joQlMMhXyEaRgJx4LrtTKMZmI4',
    appId: '1:759330275647:web:9f64d8e93b181f7499138a',
    messagingSenderId: '759330275647',
    projectId: 'rakna-47fbd',
    authDomain: 'rakna-47fbd.firebaseapp.com',
    storageBucket: 'rakna-47fbd.appspot.com',
    measurementId: 'G-JPRJB3Z4V6',
  );

}